/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSupervisionsIdRouteImport } from './routes/_authenticated/admin.supervisions.$id'
import { Route as AuthenticatedAdminProgramsProgramIdRouteImport } from './routes/_authenticated/admin.programs.$programId'
import { Route as AuthenticatedAdminClassesClassIdRouteImport } from './routes/_authenticated/admin.classes.$classId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSupervisionsIdRoute =
  AuthenticatedAdminSupervisionsIdRouteImport.update({
    id: '/admin/supervisions/$id',
    path: '/admin/supervisions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProgramsProgramIdRoute =
  AuthenticatedAdminProgramsProgramIdRouteImport.update({
    id: '/admin/programs/$programId',
    path: '/admin/programs/$programId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClassesClassIdRoute =
  AuthenticatedAdminClassesClassIdRouteImport.update({
    id: '/admin/classes/$classId',
    path: '/admin/classes/$classId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/e/$slug': typeof ESlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/classes/$classId': typeof AuthenticatedAdminClassesClassIdRoute
  '/admin/programs/$programId': typeof AuthenticatedAdminProgramsProgramIdRoute
  '/admin/supervisions/$id': typeof AuthenticatedAdminSupervisionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/e/$slug': typeof ESlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/classes/$classId': typeof AuthenticatedAdminClassesClassIdRoute
  '/admin/programs/$programId': typeof AuthenticatedAdminProgramsProgramIdRoute
  '/admin/supervisions/$id': typeof AuthenticatedAdminSupervisionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/e/$slug': typeof ESlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/classes/$classId': typeof AuthenticatedAdminClassesClassIdRoute
  '/_authenticated/admin/programs/$programId': typeof AuthenticatedAdminProgramsProgramIdRoute
  '/_authenticated/admin/supervisions/$id': typeof AuthenticatedAdminSupervisionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/e/$slug'
    | '/admin/'
    | '/admin/classes/$classId'
    | '/admin/programs/$programId'
    | '/admin/supervisions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/e/$slug'
    | '/admin'
    | '/admin/classes/$classId'
    | '/admin/programs/$programId'
    | '/admin/supervisions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/e/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/classes/$classId'
    | '/_authenticated/admin/programs/$programId'
    | '/_authenticated/admin/supervisions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ESlugRoute: typeof ESlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/supervisions/$id': {
      id: '/_authenticated/admin/supervisions/$id'
      path: '/admin/supervisions/$id'
      fullPath: '/admin/supervisions/$id'
      preLoaderRoute: typeof AuthenticatedAdminSupervisionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/programs/$programId': {
      id: '/_authenticated/admin/programs/$programId'
      path: '/admin/programs/$programId'
      fullPath: '/admin/programs/$programId'
      preLoaderRoute: typeof AuthenticatedAdminProgramsProgramIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/classes/$classId': {
      id: '/_authenticated/admin/classes/$classId'
      path: '/admin/classes/$classId'
      fullPath: '/admin/classes/$classId'
      preLoaderRoute: typeof AuthenticatedAdminClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClassesClassIdRoute: typeof AuthenticatedAdminClassesClassIdRoute
  AuthenticatedAdminProgramsProgramIdRoute: typeof AuthenticatedAdminProgramsProgramIdRoute
  AuthenticatedAdminSupervisionsIdRoute: typeof AuthenticatedAdminSupervisionsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClassesClassIdRoute: AuthenticatedAdminClassesClassIdRoute,
  AuthenticatedAdminProgramsProgramIdRoute:
    AuthenticatedAdminProgramsProgramIdRoute,
  AuthenticatedAdminSupervisionsIdRoute: AuthenticatedAdminSupervisionsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ESlugRoute: ESlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
